# Generated by Django 2.2.5 on 2021-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210720_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='', max_length=120),
        ),
    ]
