# Generated by Django 2.2.5 on 2021-04-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20210404_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Roomtype',
            new_name='room_type',
        ),
    ]
